In [2]:
import numpy as np

#### Numpy arrays

In [3]:
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# py_list = [1, 2, 3]
# print(f'python list {py_list}')

print("Single Dimentional Array: ")
print(arr_1d)
print("\n")

print("Two Dimentional Array: ")
print(arr_2d)

Single Dimentional Array: 
[1 2 3 4 5]


Two Dimentional Array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Multiplication in lists and np arrays

In [4]:
l = [1, 2, 3]
print(f'Python list Multiplication {l * 2}') # [1, 2, 3, 1, 2, 3]

np_mul = np.array([1, 2, 3])
print(f'Numpy array Multiplication {np_mul * 2}') # [2, 4, 6]

Python list Multiplication [1, 2, 3, 1, 2, 3]
Numpy array Multiplication [2 4 6]


#### Create np arrays using arange

In [ ]:
range_array = np.arange(1, 10)
print(range_array)

[ 2  4  6  8 10 12 14 16 18]
