In [ ]:
import numpy as np

In [8]:
a = np.array(
  [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
  ]
)

np.save("a.npy", a)

In [9]:
loaded_arr = np.load('a.npy')
print(loaded_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
